version: '2'
services:
  identity-provider-rts:
    build: .
    ports:
    - 3000:3000
    environment:
    - IDP_RECAPCHA_SITEKEY=6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
    - IDP_RECAPCHA_SECRETKEY=6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
    - DB_DATABASE=idp
    - DB_TYPE=postgres
    - DB_HOST=postgres
    - DB_PORT=5432
    - DB_USER=postgres
    - DB_PASSWORD=BlinkenderWaldRegnetFrohlich
    - MAIL_TRANSPORT_TYPE=smtp
    - MAIL_USER_NAME=ebu
    - MAIL_PASSWORD=rahmaiYaey2e
    - MAIL_HOST=mail.maximator.org
    - MAIL_PORT=25
    - AUTH_SESSION_COOKIE_ACCESSIBLE_OVER_NON_HTTPS=true
    - AUTH_SESSION_COOKIE_SAMESITE=lax
    - GOOGLE_LOGIN_ENABLED=true
    - GOOGLE_LOGIN_ID=428910240917-u18132kf0qrp347gjb5ddnsco6mp8u3g.apps.googleusercontent.com
    - GOOGLE_LOGIN_SECRET=9nG_oREywyfzDWwASVVFVQOr
    - FACEBOOK_LOGIN_ENABLED=true
    - FACEBOOK_LOGIN_ID=315223112568780
    - FACEBOOK_LOGIN_SECRET=ccd7c4568fb402585e4acb3eb1eb9068

    # Broadcaster custom properties
    - BROADCASTER_LAYOUT=rts
    - MAIL_DEFAULT_TEMPLATE_CLASS=rts
    - MAIL_FROM=no-reply@rts.ch
    - IDP_HOST=http://localhost.rts.ch:3000
    - BASE_URL=http://localhost.rts.ch:3000
    - DEFAULT_LOCALE=fr
    - SESSION_SECRET=LKASDMjnr234n90lasndfsadf
    depends_on:
    - postgres
    links:
    - postgres:postgres

  identity-provider-rsi:
    build: .
    ports:
    - 3001:3000
    environment:
    - IDP_RECAPCHA_SITEKEY=6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
    - IDP_RECAPCHA_SECRETKEY=6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
    - DB_DATABASE=idp
    - DB_TYPE=postgres
    - DB_HOST=postgres
    - DB_PORT=5432
    - DB_USER=postgres
    - DB_PASSWORD=BlinkenderWaldRegnetFrohlich
    - MAIL_TRANSPORT_TYPE=smtp
    - MAIL_USER_NAME=ebu
    - MAIL_PASSWORD=rahmaiYaey2e
    - MAIL_HOST=mail.maximator.org
    - MAIL_PORT=25
    - AUTH_SESSION_COOKIE_ACCESSIBLE_OVER_NON_HTTPS=true

    - GOOGLE_LOGIN_ENABLED=true
    - GOOGLE_LOGIN_ID=428910240917-u18132kf0qrp347gjb5ddnsco6mp8u3g.apps.googleusercontent.com
    - GOOGLE_LOGIN_SECRET=9nG_oREywyfzDWwASVVFVQOr
    - FACEBOOK_LOGIN_ENABLED=true
    - FACEBOOK_LOGIN_ID=315223112568780
    - FACEBOOK_LOGIN_SECRET=ccd7c4568fb402585e4acb3eb1eb9068

    # Broadcaster custom properties
    - BROADCASTER_LAYOUT=br-mediathek
    - MAIL_DEFAULT_TEMPLATE_CLASS=br-mediathek
    - MAIL_FROM=no-reply@rsi.ch
    - IDP_HOST=http://localhost.rsi.ch:3001
    - BASE_URL=http://localhost.rsi.ch:3001
    - DEFAULT_LOCALE=en
    - SESSION_SECRET=LKASDMjnr234n90lasndfsadf
    depends_on:
    - postgres
    links:
    - postgres:postgres

  postgres:
    build: postgres
    ports:
    - 5432:5432
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=BlinkenderWaldRegnetFrohlich
    - DOCKER_USER=dockeridp
    - DOCKER_PASSWORD=SchiefesHausBautFalsch
