version: '3'
services:
  # image from pipe/pipe/pipe-hadoop
  hdfs-nn:
    image: local/pipe-hadoop

  exporter:
    image: local/pipe-idp-exporter
    build: .
    environment:
    - SLEEP_DURATION=10
    - DB_HOST=192.168.1.181
    - DB_USER=dockeridp
    - PGPASSWORD=SchiefesHausBautFalsch
    - DB_NAME=idp
    - DB_PORT=5432

    - HDFS_NAMENODE=hdfs-nn
    - HDFS_DESTINATION=/idp_data.csv
